<!DOCTYPE html>
<html lang="en">
<head>
	<title>Shower Presentation Engine</title>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="shower/themes/ribbon/styles/screen-16x10.css">
</head>
<body class="shower list">

	<header class="caption">
		<h1>How to live with errors in JavaScript</h1>
	</header>

	<section class="slide" id="cover">
		<h2>How to live with errors in JavaScript</h2>
		<p>by <a href="https://github.com/numminorihsf">Konstantin Petryaev</a></p>
		<figure>
			<img class="cover" src="pictures/bsod.jpg" alt="Hands on the orange typewriter in a park">
			<figcaption class="white">
				<a>© Microsoft</a>
			</figcaption>
		</figure>
		<style>
			#cover {
				background-color: #000000;
			    }
			#cover h2 {
				margin:30px 0 0;
				color:#FFF;
				text-align:center;
				font-size:70px;
				}
			#cover p {
				margin:10px 0 0;
				text-align:center;
				color:#FFF;
				font-style:italic;
				font-size:20px;
				}
				#cover p a {
					color:#FFF;
					}
		</style>
	</section>

	<section class="slide">
		<h2>What is error</h2>
		<ul>
			<li><code>Error</code></li>
			<li><code>throw</code></li>
			<li><code>EventEmitter#emit('error')</code></li>
			<li><code>process.on('error')</code></li>
			<li><code>window.onerror</code></li>
			<li><code>window.addEventListener('error')</code></li>
			<li><code>try</code>, <code>catch</code>, <code>finally</code></li>
		</ul>
		<p class="next">We don't love them.
			<span class="next">Really.</span>
			<span class="next">Because we see it in runtime (usually).</span>
		</p>
	</section>

	<section class="slide">
		<h2>Prevent runtime error</h2>
		<ul>
			<li class="next">Docs</li>
			<li class="next"><code>"use strict"</code></li>
			<li class="next">ESLint</li>
			<li class="next">Flow / TypeScript</li>
			<li class="next">Code Review</li>
			<li class="next">Code Style</li>
			<li class="next">Tests<sup>*</sup>, Errors<sup>*</sup></li>
		</ul>
		<p class="next note">* in production runtime.</p>
	</section>

	<section class="slide">
		<h2>Throw</h2>
		<ol>
			<li><code>throw null;</code></li>
			<li><code>throw 11;</code></li>
			<li><code>throw 'We have some problem';</code></li>
			<li><code>throw new Error('We have some problem');</code></li>
		</ol>
		<p class="next">Use only 4th.</p>
		<p class="next">One of the reasons is that usually error handlers waiting for <code>Error</code>'s instance.</p>
	</section>

	<section class="slide">
		<h2>Error#stack</h2>
		<code>error.stack</code>
		<pre>
			<code class="mark">ReferenceError: event is not defined       tag.js:214:120</code>
			<code>h             https://mc.yandex.ru/metrika/tag.js:214:120</code>
			<code>bound h                                self-hosted:913:17</code>
			<code>value/<         https://mc.yandex.ru/metrika/tag.js:47:72</code>
			<code>bound                                  self-hosted:913:17</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Try/Catch/Finally</h2>
		<pre>
			<code>try {</code>
			<code>  throw new Error('My error');</code>
			<code>} catch (error) {</code>
			<code>  console.error(error);</code>
			<code>}</code>
			<code class="next comment">// My error</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Try/Catch/Finally</h2>
		<pre>
			<code>try {</code>
			<code>  throw new Error('My error');</code>
			<code>} finally {</code>
			<code>  console.log('end');</code>
			<code>}</code>
			<code class="next comment">// end</code>
			<code class="next comment">// My error</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Try/Catch/Finally</h2>
		<pre>
			<code>try {</code>
			<code>  throw new Error('My error');</code>
			<code>} catch (error) {</code>
			<code>  console.error(error);</code>
			<code>} finally {</code>
			<code>  console.log('end');</code>
			<code>}</code>
			<code class="next comment">// My error</code>
			<code class="next comment">// end</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Try/Catch/Finally</h2>
		<pre>
			<code>try {</code>
			<code>  return 1;</code>
			<code>} catch (error) {</code>
			<code>  return 2;</code>
			<code>} finally {</code>
			<code>  return 3;</code>
			<code>}</code>
			<code class="next comment">// 3</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Try/Catch/Finally</h2>
		<pre>
			<code>try {</code>
			<code>  throw ...;</code>
			<code>} catch (error) {</code>
			<code>  if (error instanceof MyError) console.error('My error');</code>
			<code>  else if (error.name === 'Error') console.error('Created error');</code>
			<code>  else console.error('Engine error');</code>
			<code>}</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Promise</h2>
		<pre>
			<code>new Promise(() => {</code>
			<code>  throw new Error();</code>
			<code>})</code>
			<code>  .catch(err => console.error(err) })</code>
			<code>  .then(() => console.log('all if ok'));</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Promise</h2>
		<pre>
			<code>new Promise(() => {</code>
			<code>  throw new Error();</code>
			<code>})</code>
			<code>  .then(onSuccess1, onError1)</code>
			<code>  .then(onSuccess2, onError2)</code>
			<code>  .then(onSuccess3, onError3)</code>
			<code>  .catch(() => console.error('global error'));</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Promise</h2>
		<pre>
			<code>new Promise(() => {</code>
			<code>  throw new Error();</code>
			<code>})</code>
			<code>  .then(() => console.log('all if ok'));</code>
			<code class="next comment">// unhandled promise rejection</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Promise</h2>
		<pre>
			<code>new Promise(() => {</code>
			<code>  throw new Error();</code>
			<code>});</code>
			<code>window.onunhandledrejection = function(rejectedPromise){</code>
			<code class="next comment"> // do everything you want</code>
			<code>};</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Async throw</h2>
		<pre>
			<code>try {</code>
			<code>  setTimeout(function(){</code>
			<code>    throw new Error('Can\'t catch');</code>
			<code>  }, 0);</code>
			<code>} catch (error) {}</code>
		</pre>
	</section>

	<section class="slide">
		<h2>Async ecxeption</h2>
		<pre>
			<code>try {</code>
			<code>  const a = await rejection;</code>
			<code>} catch (error) {</code>
			<code class="next comment">  // error from reject</code>
			<code>}</code>
		</pre>
	</section>

	<footer class="badge">
		<a href="https://github.com/shower/shower">Fork me on GitHub</a>
	</footer>

	<div class="progress"></div>

	<script src="shower/shower.min.js"></script>
	<!-- Copyright © 2017 Yours Truly, Famous Inc. -->

</body>
</html>
